package tdsi2025.mcs.enums;

public enum CryptoPrimitiveType {

     ENCRYPTION, DECRYPTION, SIGNATURE, VERIFICATION, HASHING, KEY_DERIVATION, KEY_GENERATION, KEY_EXCHANGE, KEY_WRAPPING, KEY_UNWRAPPING, HMAC, HASH
}
