spring.application.name=backend

# Configuration du port du serveur
server.port=8082

# Configuration OAuth2 avec Keycloak
spring.security.oauth2.client.registration.keycloak.client-id=backend-client
spring.security.oauth2.client.registration.keycloak.client-secret=VV0HkInhuScm19cfzoMnPUktuKOcFSIv
spring.security.oauth2.client.registration.keycloak.scope=openid, profile
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/crypto-platform

# Configuration du JWT pour le serveur de ressources
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/crypto-platform

# Configuration de la base de donnees PostgresSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/sqlCrypto
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configuration du dialecte Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Strategies de mise a jour du schema de la base de donnees
spring.jpa.hibernate.ddl-auto=update

# Configuration de Hibernate Search
spring.jpa.properties.hibernate.search.autoregister_listeners=true

# Configuration de Hibernate Validator
spring.jpa.properties.hibernate.validator.apply_to_ddl=false

# Des actives le cache de deuxième niveau d'Hibernate
spring.jpa.properties.hibernate.cache.use_second_level_cache=false

# Activer les journaux de débogage de Spring
logging.level.org.springframework=DEBUG
#logging.level.root=DEBUG
logging.level.org.springframework.security=DEBUG

#crypto.key-storage-path=src/main/resources/keys
#crypto.provider=BC

kms.masterKeyBase64=Q5NnL2p1F8x4m7wM9l8u+o+3qZ5B7j1B1j4V9g2R3FY=

app.upload-dir=src/main/resources/static/crypto/uploads
